version: '3.10.16'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_storage:/app/chroma_storage
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - CHROMADB_DIR=/app/chroma_storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: python:3.10-16
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    command: >
      bash -c "
        pip install streamlit requests &&
        streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
      "
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:8000

volumes:
  chroma_storage:
  logs:
  uploads: